/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aes_gui;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author pvlon
 */
public class AES_GUI extends javax.swing.JFrame {

    /**
     * Creates new form AES_GUI
     */
    public AES_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKeySize_E = new javax.swing.ButtonGroup();
        buttonGroupOutputFormat_E = new javax.swing.ButtonGroup();
        buttonGroupKeySize_D = new javax.swing.ButtonGroup();
        buttonGroupInputFormat_D = new javax.swing.ButtonGroup();
        buttonGroupKeySize_File = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldKey_E = new javax.swing.JTextField();
        jRadioButton128_E = new javax.swing.JRadioButton();
        jRadioButton192_E = new javax.swing.JRadioButton();
        jRadioButton256_E = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonBASE64_E = new javax.swing.JRadioButton();
        jRadioButtonHEX_E = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPlaintext_E = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCiphertext_E = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonEncrypt = new javax.swing.JButton();
        jButtonOpenFile_E = new javax.swing.JButton();
        jButtonSaveFile_E = new javax.swing.JButton();
        jButtonDeletePlaintext_E = new javax.swing.JButton();
        jButtonDeleteCiphertext_E = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaCiphertext_D = new javax.swing.JTextArea();
        jRadioButtonBASE64_D = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonDecrypt = new javax.swing.JButton();
        jTextFieldKey_D = new javax.swing.JTextField();
        jRadioButton256_D = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton128_D = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaPlaintext_D = new javax.swing.JTextArea();
        jRadioButtonHEX_D = new javax.swing.JRadioButton();
        jRadioButton192_D = new javax.swing.JRadioButton();
        jButtonOpenFile_D = new javax.swing.JButton();
        jButtonSaveFile_D = new javax.swing.JButton();
        jButtonDeleteCiphertext_D = new javax.swing.JButton();
        jButtonDeletePlaintext_D = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonOpenFile_File = new javax.swing.JButton();
        jButtonEncryptFile = new javax.swing.JButton();
        jButtonDecryptFile = new javax.swing.JButton();
        jRadioButton128_File = new javax.swing.JRadioButton();
        jRadioButton192_File = new javax.swing.JRadioButton();
        jRadioButton256_File = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldKey_File = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHUẨN AES VÀ ỨNG DỤNG TRONG MÃ HÓA DỮ LIỆU");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("CHUẨN AES VÀ ỨNG DỤNG TRONG MÃ HÓA DỮ LIỆU");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MÃ HÓA VĂN BẢN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1028, 300));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kích thước khóa:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Khóa bí mật:");

        jTextFieldKey_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroupKeySize_E.add(jRadioButton128_E);
        jRadioButton128_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton128_E.setSelected(true);
        jRadioButton128_E.setText("128 bit");
        jRadioButton128_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton128_EActionPerformed(evt);
            }
        });

        buttonGroupKeySize_E.add(jRadioButton192_E);
        jRadioButton192_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton192_E.setText("192 bit");

        buttonGroupKeySize_E.add(jRadioButton256_E);
        jRadioButton256_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton256_E.setText("256 bit");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Định dạng đầu ra:");

        buttonGroupOutputFormat_E.add(jRadioButtonBASE64_E);
        jRadioButtonBASE64_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonBASE64_E.setText("BASE64");

        buttonGroupOutputFormat_E.add(jRadioButtonHEX_E);
        jRadioButtonHEX_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonHEX_E.setSelected(true);
        jRadioButtonHEX_E.setText("HEX");

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextAreaPlaintext_E.setColumns(20);
        jTextAreaPlaintext_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaPlaintext_E.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPlaintext_E);

        jTextAreaCiphertext_E.setColumns(20);
        jTextAreaCiphertext_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaCiphertext_E.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCiphertext_E);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Bản rõ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Bản mã:");

        jButtonEncrypt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEncrypt.setText("Mã hóa");
        jButtonEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncryptActionPerformed(evt);
            }
        });

        jButtonOpenFile_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonOpenFile_E.setText("Mở file .txt");
        jButtonOpenFile_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFile_EActionPerformed(evt);
            }
        });

        jButtonSaveFile_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSaveFile_E.setText("Lưu File .txt");
        jButtonSaveFile_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveFile_EActionPerformed(evt);
            }
        });

        jButtonDeletePlaintext_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDeletePlaintext_E.setText("Xóa");
        jButtonDeletePlaintext_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePlaintext_EActionPerformed(evt);
            }
        });

        jButtonDeleteCiphertext_E.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDeleteCiphertext_E.setText("Xóa");
        jButtonDeleteCiphertext_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCiphertext_EActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel5)
                        .addGap(334, 334, 334)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldKey_E, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonHEX_E)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonBASE64_E))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton128_E)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton192_E)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton256_E))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEncrypt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDeletePlaintext_E)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonOpenFile_E))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDeleteCiphertext_E)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSaveFile_E))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEncrypt)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonOpenFile_E)
                                .addComponent(jButtonDeletePlaintext_E))
                            .addComponent(jButtonSaveFile_E)
                            .addComponent(jButtonDeleteCiphertext_E)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldKey_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton128_E)
                            .addComponent(jRadioButton192_E)
                            .addComponent(jRadioButton256_E))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonBASE64_E)
                            .addComponent(jRadioButtonHEX_E))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GIẢI MÃ VĂN BẢN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Khóa bí mật:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Định dạng đầu vào:");

        jScrollPane4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextAreaCiphertext_D.setColumns(20);
        jTextAreaCiphertext_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaCiphertext_D.setRows(5);
        jScrollPane4.setViewportView(jTextAreaCiphertext_D);

        buttonGroupInputFormat_D.add(jRadioButtonBASE64_D);
        jRadioButtonBASE64_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonBASE64_D.setText("BASE64");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Kích thước khóa:");

        jButtonDecrypt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDecrypt.setText("Giải mã");
        jButtonDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecryptActionPerformed(evt);
            }
        });

        jTextFieldKey_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroupKeySize_D.add(jRadioButton256_D);
        jRadioButton256_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton256_D.setText("256 bit");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Bản mã:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Bản rõ:");

        buttonGroupKeySize_D.add(jRadioButton128_D);
        jRadioButton128_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton128_D.setSelected(true);
        jRadioButton128_D.setText("128 bit");
        jRadioButton128_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton128_DActionPerformed(evt);
            }
        });

        jTextAreaPlaintext_D.setColumns(20);
        jTextAreaPlaintext_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaPlaintext_D.setRows(5);
        jScrollPane3.setViewportView(jTextAreaPlaintext_D);

        buttonGroupInputFormat_D.add(jRadioButtonHEX_D);
        jRadioButtonHEX_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonHEX_D.setSelected(true);
        jRadioButtonHEX_D.setText("HEX");

        buttonGroupKeySize_D.add(jRadioButton192_D);
        jRadioButton192_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton192_D.setText("192 bit");

        jButtonOpenFile_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonOpenFile_D.setText("Mở File .txt");
        jButtonOpenFile_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFile_DActionPerformed(evt);
            }
        });

        jButtonSaveFile_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSaveFile_D.setText("Lưu File .txt");
        jButtonSaveFile_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveFile_DActionPerformed(evt);
            }
        });

        jButtonDeleteCiphertext_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDeleteCiphertext_D.setText("Xóa");
        jButtonDeleteCiphertext_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCiphertext_DActionPerformed(evt);
            }
        });

        jButtonDeletePlaintext_D.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDeletePlaintext_D.setText("Xóa");
        jButtonDeletePlaintext_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePlaintext_DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldKey_D, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton128_D)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton192_D)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton256_D)))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButtonHEX_D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonBASE64_D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonDecrypt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDeleteCiphertext_D)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonOpenFile_D)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonDeletePlaintext_D)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSaveFile_D)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDecrypt)
                            .addComponent(jButtonOpenFile_D)
                            .addComponent(jButtonDeleteCiphertext_D)
                            .addComponent(jButtonSaveFile_D)
                            .addComponent(jButtonDeletePlaintext_D)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldKey_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton128_D)
                            .addComponent(jRadioButton192_D)
                            .addComponent(jRadioButton256_D))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonHEX_D)
                            .addComponent(jRadioButtonBASE64_D))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MÃ HÓA VÀ GIẢI MÃ FILE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jTextFieldPath.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPath.setText("Mở File hoặc nhập đường dẫn tại đây...!");

        jButtonOpenFile_File.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonOpenFile_File.setText("Mở File");
        jButtonOpenFile_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFile_FileActionPerformed(evt);
            }
        });

        jButtonEncryptFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEncryptFile.setText("Mã hóa File");
        jButtonEncryptFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncryptFileActionPerformed(evt);
            }
        });

        jButtonDecryptFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDecryptFile.setText("Giải mã File");
        jButtonDecryptFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecryptFileActionPerformed(evt);
            }
        });

        buttonGroupKeySize_File.add(jRadioButton128_File);
        jRadioButton128_File.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton128_File.setSelected(true);
        jRadioButton128_File.setText("128 bit");
        jRadioButton128_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton128_FileActionPerformed(evt);
            }
        });

        buttonGroupKeySize_File.add(jRadioButton192_File);
        jRadioButton192_File.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton192_File.setText("192 bit");

        buttonGroupKeySize_File.add(jRadioButton256_File);
        jRadioButton256_File.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton256_File.setText("256 bit");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Khóa bí mật:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Kích thước khóa:");

        jTextFieldKey_File.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldKey_File, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton128_File)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton192_File)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton256_File)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonEncryptFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDecryptFile))
                    .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOpenFile_File)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKey_File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenFile_File))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonEncryptFile)
                        .addComponent(jButtonDecryptFile))
                    .addComponent(jLabel14))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton128_File)
                    .addComponent(jRadioButton192_File)
                    .addComponent(jRadioButton256_File))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton128_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton128_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton128_EActionPerformed

    private void jButtonEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncryptActionPerformed
        String key = jTextFieldKey_E.getText();
        String plaintext = jTextAreaPlaintext_E.getText();
        String ciphertext = "";
        if(jRadioButton128_E.isSelected()) {
            if(key.length() != 16) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
            if(jRadioButtonHEX_E.isSelected()) {
                ciphertext = AES128.encrypt_hex(plaintext, key);
            }
            else if(jRadioButtonBASE64_E.isSelected()) {
                ciphertext = AES128.encrypt_base64(plaintext, key);
            }
        }
        else if(jRadioButton192_E.isSelected()) {
            if(key.length() != 24) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
            if(jRadioButtonHEX_E.isSelected()) {
                ciphertext = AES192.encrypt_hex(plaintext, key);
            }
            else if(jRadioButtonBASE64_E.isSelected()) {
                ciphertext = AES192.encrypt_base64(plaintext, key);
            }
        }
        else if(jRadioButton256_E.isSelected()) {
            if(key.length() != 32) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
            if(jRadioButtonHEX_E.isSelected()) {
                ciphertext = AES256.encrypt_hex(plaintext, key);
            }
            else if(jRadioButtonBASE64_E.isSelected()) {
                ciphertext = AES256.encrypt_base64(plaintext, key);
            }
        }
        jTextAreaCiphertext_E.setText(ciphertext);
    }//GEN-LAST:event_jButtonEncryptActionPerformed

    private void jRadioButton128_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton128_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton128_DActionPerformed

    private void jButtonDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecryptActionPerformed
        String key = jTextFieldKey_D.getText();
        String ciphertext = jTextAreaCiphertext_D.getText();
        String plaintext = "";
        if(jRadioButton128_D.isSelected()) {
            if(key.length() != 16) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
            if(jRadioButtonHEX_D.isSelected()) {
                plaintext = AES128.decrypt_hex(ciphertext, key);
            }
            if(jRadioButtonBASE64_D.isSelected()) {
                plaintext = AES128.decrypt_base64(ciphertext, key);
            }
        }
        else if(jRadioButton192_D.isSelected()) {
            if(key.length() != 24) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
            if(jRadioButtonHEX_D.isSelected()) {
                plaintext = AES192.decrypt_hex(ciphertext, key);
            }
            if(jRadioButtonBASE64_D.isSelected()) {
                plaintext = AES192.decrypt_base64(ciphertext, key);
            }
        }
        else if(jRadioButton256_D.isSelected()) {
            if(key.length() != 32) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
            if(jRadioButtonHEX_D.isSelected()) {
                plaintext = AES256.decrypt_hex(ciphertext, key);
            }
            if(jRadioButtonBASE64_D.isSelected()) {
                plaintext = AES256.decrypt_base64(ciphertext, key);
            }
        }
        if(plaintext.equals("Không hợp lệ!")) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không toàn vẹn!");
            jTextAreaPlaintext_D.setText("");
            return;
        }
        jTextAreaPlaintext_D.setText(plaintext);
    }//GEN-LAST:event_jButtonDecryptActionPerformed

    private void jButtonOpenFile_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFile_EActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Text Files", "txt"));
        
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                jTextAreaPlaintext_E.setText("");
                String line;
                while ((line = reader.readLine()) != null) {
                    jTextAreaPlaintext_E.append(line + "\n");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc File: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonOpenFile_EActionPerformed

    private void jButtonSaveFile_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveFile_EActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Text Files", "txt"));
        fileChooser.setSelectedFile(new File("EncryptedFile"));

        int result = fileChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
                writer.write(jTextAreaCiphertext_E.getText());
                JOptionPane.showMessageDialog(this, "Lưu File thành công!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi lưu File: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSaveFile_EActionPerformed

    private void jButtonOpenFile_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFile_DActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Text Files", "txt"));

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                jTextAreaCiphertext_D.setText("");
                String line;
                while ((line = reader.readLine()) != null) {
//                    jTextAreaCiphertext_D.append(line + "\n");
                    jTextAreaCiphertext_D.append(line);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi đọc File: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonOpenFile_DActionPerformed

    private void jButtonSaveFile_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveFile_DActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Text Files", "txt"));
        fileChooser.setSelectedFile(new File("DecryptedFile"));

        int result = fileChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
                writer.write(jTextAreaPlaintext_D.getText());
                JOptionPane.showMessageDialog(this, "Lưu File thành công!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi lưu File: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSaveFile_DActionPerformed

    private void jButtonDeletePlaintext_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePlaintext_EActionPerformed
        jTextAreaPlaintext_E.setText("");
    }//GEN-LAST:event_jButtonDeletePlaintext_EActionPerformed

    private void jButtonDeleteCiphertext_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCiphertext_EActionPerformed
        jTextAreaCiphertext_E.setText("");
    }//GEN-LAST:event_jButtonDeleteCiphertext_EActionPerformed

    private void jButtonDeleteCiphertext_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCiphertext_DActionPerformed
        jTextAreaCiphertext_D.setText("");
    }//GEN-LAST:event_jButtonDeleteCiphertext_DActionPerformed

    private void jButtonDeletePlaintext_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePlaintext_DActionPerformed
        jTextAreaPlaintext_D.setText("");
    }//GEN-LAST:event_jButtonDeletePlaintext_DActionPerformed

    private void jRadioButton128_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton128_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton128_FileActionPerformed

    private void jButtonOpenFile_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFile_FileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File file = chooser.getSelectedFile();
        jTextFieldPath.setText(file.getAbsolutePath());
    }//GEN-LAST:event_jButtonOpenFile_FileActionPerformed

    private void jButtonEncryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncryptFileActionPerformed
        String inputKey = jTextFieldKey_File.getText();
        if(jRadioButton128_File.isSelected()) {
            if(inputKey.length() != 16) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
        }
        else if(jRadioButton192_File.isSelected()) {
            if(inputKey.length() != 24) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
        }
        else if(jRadioButton256_File.isSelected()) {
            if(inputKey.length() != 32) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
        }
        
        try {
            FileInputStream fileInput = new FileInputStream(jTextFieldPath.getText());

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setSelectedFile(new File("EncryptedFile"));

            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection != JFileChooser.APPROVE_OPTION) {
                return;
            }

            File fileToSave = fileChooser.getSelectedFile();
            FileOutputStream fileOuput = new FileOutputStream(fileToSave);

            byte[] k = inputKey.getBytes();
            SecretKeySpec key = new SecretKeySpec(k, "AES");
            Cipher encrypt = Cipher.getInstance("AES");
            encrypt.init(Cipher.ENCRYPT_MODE, key);

            CipherOutputStream cos = new CipherOutputStream(fileOuput, encrypt);
            byte[] buf = new byte[1024];
            int read;
            while ((read = fileInput.read(buf)) != -1) {
                cos.write(buf, 0, read);
            }
            fileInput.close();
            fileOuput.flush();
            cos.close();

            JOptionPane.showMessageDialog(this, "File đã được mã hóa");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đường dẫn không hợp lệ hoặc File không tồn tại! Vui lòng kiểm tra lại!");
        }
    }//GEN-LAST:event_jButtonEncryptFileActionPerformed

    private void jButtonDecryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecryptFileActionPerformed
        String inputKey = jTextFieldKey_File.getText();
        if(jRadioButton128_File.isSelected()) {
            if(inputKey.length() != 16) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
        }
        else if(jRadioButton192_File.isSelected()) {
            if(inputKey.length() != 24) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
        }
        else if(jRadioButton256_File.isSelected()) {
            if(inputKey.length() != 32) {
                JOptionPane.showMessageDialog(this, "Khóa bị thay đổi! Vui lòng kiểm tra lại kích thước và nội dung khóa!");
                return;
            }
        }
        
        try {
            FileInputStream fileInput = new FileInputStream(jTextFieldPath.getText());
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setSelectedFile(new File("DecryptedFile"));
            int userSelection = fileChooser.showSaveDialog(this);
            
            if (userSelection != JFileChooser.APPROVE_OPTION) {
                return;
            }
            
            File fileToSave = fileChooser.getSelectedFile();
            FileOutputStream fileOutput = new FileOutputStream(fileToSave);
            
            byte k[] = inputKey.getBytes();
            SecretKeySpec key = new SecretKeySpec(k, "AES");
            Cipher decrypt = Cipher.getInstance("AES");
            decrypt.init(Cipher.DECRYPT_MODE, key);
            
            CipherOutputStream cos = new CipherOutputStream(fileOutput, decrypt);
            byte[] buf = new byte[1024];
            int read;
            while ((read = fileInput.read(buf)) != -1) {
                cos.write(buf, 0, read);
            }
            fileInput.close();
            fileOutput.flush();
            cos.close();
            JOptionPane.showMessageDialog(this, "Giải mã thành công!");
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + fileToSave.getAbsolutePath());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đường dẫn không hợp lệ hoặc File không tồn tại! Vui lòng kiểm tra lại!");
        }
    }//GEN-LAST:event_jButtonDecryptFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AES_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInputFormat_D;
    private javax.swing.ButtonGroup buttonGroupKeySize_D;
    private javax.swing.ButtonGroup buttonGroupKeySize_E;
    private javax.swing.ButtonGroup buttonGroupKeySize_File;
    private javax.swing.ButtonGroup buttonGroupOutputFormat_E;
    private javax.swing.JButton jButtonDecrypt;
    private javax.swing.JButton jButtonDecryptFile;
    private javax.swing.JButton jButtonDeleteCiphertext_D;
    private javax.swing.JButton jButtonDeleteCiphertext_E;
    private javax.swing.JButton jButtonDeletePlaintext_D;
    private javax.swing.JButton jButtonDeletePlaintext_E;
    private javax.swing.JButton jButtonEncrypt;
    private javax.swing.JButton jButtonEncryptFile;
    private javax.swing.JButton jButtonOpenFile_D;
    private javax.swing.JButton jButtonOpenFile_E;
    private javax.swing.JButton jButtonOpenFile_File;
    private javax.swing.JButton jButtonSaveFile_D;
    private javax.swing.JButton jButtonSaveFile_E;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton128_D;
    private javax.swing.JRadioButton jRadioButton128_E;
    private javax.swing.JRadioButton jRadioButton128_File;
    private javax.swing.JRadioButton jRadioButton192_D;
    private javax.swing.JRadioButton jRadioButton192_E;
    private javax.swing.JRadioButton jRadioButton192_File;
    private javax.swing.JRadioButton jRadioButton256_D;
    private javax.swing.JRadioButton jRadioButton256_E;
    private javax.swing.JRadioButton jRadioButton256_File;
    private javax.swing.JRadioButton jRadioButtonBASE64_D;
    private javax.swing.JRadioButton jRadioButtonBASE64_E;
    private javax.swing.JRadioButton jRadioButtonHEX_D;
    private javax.swing.JRadioButton jRadioButtonHEX_E;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaCiphertext_D;
    private javax.swing.JTextArea jTextAreaCiphertext_E;
    private javax.swing.JTextArea jTextAreaPlaintext_D;
    private javax.swing.JTextArea jTextAreaPlaintext_E;
    private javax.swing.JTextField jTextFieldKey_D;
    private javax.swing.JTextField jTextFieldKey_E;
    private javax.swing.JTextField jTextFieldKey_File;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
